export type User = {
  id: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  isAuthorized: boolean;
  imported: boolean;
  teamId: string;
  role: string;
  linkedinLink: string | null;
  isReceivingNotifications: boolean;
  avatarKey: string | undefined;
  loggedInAt: string;
  createdAt: string;
  updatedAt: string | null;
  deletedAt: string | null;
};

export type Company = {
  id: string;
  zoomInfoId: number | null;
  name: string;
  logo: string | undefined;
  ticker: string | null;
  parentCompany: string | null;
  phone: number;
  fax: string | null;
  website: string | null;
  city: string;
  street: string;
  state: string | null;
  zipCode: string;
  country: string;
  continent: string | null;
  productsBrandDescription: string | null;
  descriptionList: string | null;
  revenueRange: string | null;
  employeeRange: string | null;
  twitterHandle: string | null;
  socialMediaUrls: Array<Array<string>> | null;
  competitors: string | null;
  subUnitIndustries: string | null;
  primaryIndustry: Array<string>;
  industries: Array<string> | null;
  revenue: string | null;
  employeeCount: number;
  annualContributions: string | null;
  cashContributions: string | null;
  inKindContributions: string | null;
  employeeContributions: string | null;
  parentId: string | null;
  parentName: string | null;
  type: string | null;
  sdgGoals: string | null;
  genders: string | null;
  income: string | null;
  age: string | null;
  ethnicity: any;
  nonprofit: any;
  purchase: any;
  affiliation: any;
  brands: any;
  interests: any;
  typesOfInvestment: any;
  errorLoadZoomInfo: any;
  charitablePartners: Array<any>;
  statusZoomInfo: string | null;
  loadZoomInfoDate: any;
  errorLoadZoomInfoDate: any;
  partnershipLink: string | null;
  employeeEngagementOpportunities: any;
  similarCompanies: Array<string> | null;
  favoriteCompanies: Array<any>;
  score: number;
  like: boolean;
  crsFocus: Array<any>;
};

export interface Meta {
  totalItems: number;
  itemCount: number;
  itemsPerPage: string;
  totalPages: number;
  currentPage: string;
}

export type SignInDto = {
  email: string;
  password: string;
};
